### ISSUE TITLE
Spell check doesn't work

### ISSUE THREAD

**Issue by freb** [tbh1/sublime-notes#9]
I've been using this for a few months now and love it. I noticed that on both my Linux and Windows installations, whenever I'm using the Notes syntax, spell check doesn't work. It just comes back with 0 misspelled words.

I've never created a similar package for Sublime so am not sure of the cause. I just wanted to see if you were aware. If you are and don't have a fix, I'll see if I can do some investigation.

**Comment by enaito** [comment]
Spell check only seems to work in quoted text, but not otherwise. I've played around with it for a while and don't see any way to adjust this.

**Comment by tbh1** [comment]
Hi, spell check doesn't currently work outside of strings due to the .notes syntax being considered a `source` language as opposed to a text language.

From the docs: ```scopeName
Name of the topmost scope for this syntax definition. Either source.<lang> or text.<lang>. Use source for programming languages and text for markup and everything else.```

We could switch this to a text based language, but there are some side effects:
- intellisense won't work (tab-complete will)
- all code snippets will be spell-checked

Another option is adding an additional syntax: `Notes - Text`, that is treated as a text language. You'll need to toggle the syntax for proof-reading, but it won't affect code snippets.

<img width="683" alt="screen shot 2016-04-26 at 1 39 20 pm" src="https://cloud.githubusercontent.com/assets/5551627/14830314/1a937c2e-0bbe-11e6-8777-fb35724707e3.png">

I'll go ahead with this option, if it's causing problems for people I'll switch to a text language by default.
